### ISSUE TITLE
libpng16.so.16 is missing in the AppImage

### ISSUE THREAD

**Issue by probonopd** [filipestevao/AlphaPlot-AppImage#1]
Hi @filipestevao, thanks for making an AppImage.

I am getting:

```
alphaplot: error while loading shared libraries: libpng16.so.16: cannot open shared object file: No such file or directory
```

The library needs to be bundled.

Reference:
https://github.com/AppImage/appimage.github.io/pull/2068

**Comment by filipestevao** [comment]
Hi @probonopd,

I will work on it.

Thank you.

**Comment by filipestevao** [comment]
Hi @probonopd,

The `libpng` library was included.

Can you test this image?

https://github.com/filipestevao/AlphaPlot-AppImage/releases/download/v1.011-alpha/AlphaPlot-1.011-alpha-release.glibc2.29-x86_64.AppImage

**Comment by probonopd** [comment]
```
me@host:~$ Downloads/AlphaPlot-1.011-alpha-release.glibc2.29-x86_64.AppImage 
alphaplot: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by alphaplot)
```

This means that the system the AppImage was made with was newer than the system I am trying to run it on. Can you use the oldest still-supported LTS (currently xenial) to put together the AppImage? Then, it should run on all still-supported Ubuntu releases (and other similarly "old" distributions).

**Comment by filipestevao** [comment]
Continued in #2
