### ISSUE TITLE
Fails to run on Xubuntu 18.04.4 LTS

### ISSUE THREAD

**Issue by probonopd** [filipestevao/AlphaPlot-AppImage#2]
Fails to run on Xubuntu 18.04.4 LTS because it was compiled on a too new system. Please compile on e.g., xenial for better compatibility with older distribution releases. Thank you!

```
me@host:~$ Downloads/AlphaPlot-1.011-alpha-release.glibc2.29-x86_64.AppImage 
alphaplot: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by alphaplot)

me@host:~$ cat /etc/os-release 
NAME="Ubuntu"
VERSION="18.04.4 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.4 LTS"
```

**Comment by filipestevao** [comment]
Hello @probonopd,

I am aware of this issue. I even discussed this with the owner of the AlphaPlot repository [here](https://github.com/narunlifescience/AlphaPlot/issues/18#issue-639917038).

I read the AppImage docs and the "[best practices](https://docs.appimage.org/reference/best-practices.html#binaries-compiled-on-old-enough-base-system)". First, it was very difficult to get the necessary libraries. In addition, even trying to compile the program on  older base systems, the source code uses Qt features that are only present in recent versions and this has caused many errors.

I really don't know how to solve this issue. Maybe someone with more knowledge about compiling source code and Qt libraries can help.

**Comment by probonopd** [comment]
>  the source code uses Qt features that are only present in recent versions

Which Qt version is needed? https://launchpad.net/~beineri currently has Qt 5.15.0 for xenial:
https://launchpad.net/~beineri/+archive/ubuntu/opt-qt-5.15.0-xenial

Wouldn't that work?

**Comment by filipestevao** [comment]
I believe that Qt 5.15.0 will work.

This AppImage was built using the ArchLinux libraries. I didn't try to use PPA.

**Comment by probonopd** [comment]
Using xenial plus that PPA would probably result in an AppImage that could run on many more systems than the current one, so it may be worthwhile.

**Comment by filipestevao** [comment]
Hi @probonopd,

Due to personal reasons, this repository will be archived.

If you need this app, [AlphaPlot is available to install from Flathub](https://flathub.org/apps/details/io.github.narunlifescience.AlphaPlot).

Thank you for your contribution and keep up the good work with the AppImage.
